apiVersion: v1
kind: Deployment
metadata:
  name: kubernetes-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-example
  template:
    metadata:
      labels:
        app: kubernetes-example
    spec:
      containers:
      - name: kubernetes-example
        image: 4726/kubernetes-example:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - containerPort: 14000 