apiVersion: v1
kind: Service                    
metadata:
  name: kubernetes-example
spec:
  type: NodePort                
  ports:                        
  - name: http
    port: 14000
    targetPort: 14000
  selector:
    app: kubernetes-example     